version: '3'
services:
  server:
    build: ./server
    expose:
      - 8000
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/app/server
    command: npm start
  
  client:
    build: ./client
    environment:
      - REACT_APP_PORT:${REACT_APP_PORT}
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/app/client/src
      - ./client/dist:/usr/app/client/dist
    links:
      - server
    depends_on:
      - server
    command: npm start
