version: '3'
services:
  server:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/app
    command: npm start
  
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - '/usr/src/app/node_modules'
    links:
      - server
    depends_on:
      - server
    command: npm start
